FROM php:8.2-apache

WORKDIR /var/www/html

COPY conexao.php /var/www/html/
COPY index.php /var/www/html/

RUN apt-get update && apt-get install -y libzip-dev libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd zip \ 
    && docker-php-ext-install mysqli pdo pdo_mysql

EXPOSE 80